vim.cmd.highlight 'clear'
vim.g.colors_name = 'cold'
local h = vim.api.nvim_set_hl
vim.opt.termguicolors = true
if vim.o.background == 'dark' then
    h(0, 'Directory', { fg = '#739393' })
    h(0, 'Normal', { bg = '#0e0e0e', fg = '#c8c8c8' })
    h(0, 'DiagnosticOk', { fg = '#9EBC9F' })
    h(0, 'ErrorMsg', { fg = '#ab4642' })
    h(0, 'String', { fg = '#9EBC9F', italic = false })
    h(0, 'StatusLineGitBranchIcon', { bg = '#161616', fg = '#dc9656' })
    h(0, 'StatusLineGitDiffRemoved', { bg = '#161616', fg = '#ab4642' })
    h(0, 'Number', { fg = '#d8d8d8' })
    h(0, 'StatusLineGitDiffAdded', { bg = '#161616', fg = '#9EBC9F' })
    h(0, 'StatusLineLspInactive', { bg = '#111111', fg = '#ab4642' })
    h(0, 'StatusLineLspActive', { bg = '#161616', fg = '#9EBC9F' })
    h(0, 'StatusLineLspMessages', { bg = '#111111', fg = '#739393' })
    h(0, 'StatusLineLspInfo', { bg = '#161616', fg = '#739393' })
    h(0, 'Title', { fg = '#d8d8d8' })
    h(0, 'StatusLineLspWarn', { bg = '#161616', fg = '#f7ca88' })
    h(0, 'StatusLineLspError', { bg = '#161616', fg = '#ab4642' })
    h(0, 'StatusLineNeovimLogo', { bg = '#76946A', fg = '#111111' })
    h(0, 'StatusLineMedium', { bg = '#161616', fg = '#787878' })
    h(0, 'DiagnosticFloatingError', { link = 'DiagnosticError' })
    h(0, 'Visual', { bg = '#383838' })
    h(0, 'Type', { fg = '#a8a8a8', italic = false })
    h(0, 'Structure', { fg = '#a8a8a8' })
    h(0, 'DiagnosticSignOk', { link = 'DiagnosticOk' })
    h(0, 'DiagnosticHint', { fg = '#86c1b9' })
    h(0, 'DiagnosticInfo', { fg = '#739393' })
    h(0, 'DiagnosticWarn', { fg = '#f7ca88' })
    h(0, 'DiagnosticError', { fg = '#ab4642' })
    h(0, 'DiagnosticFloatingOk', { link = 'DiagnosticOk' })
    h(0, 'DiagnosticUnderlineOk', { special = '#9EBC9F', undercurl = true })
    h(0, 'WarningMsg', { fg = '#f7ca88' })
    h(0, '@lsp.typemod.keyword.async', { link = 'Keyword' })
    h(0, '@tag.tsx', { link = 'Type' })
    h(0, '@tag.javascript', { link = 'Type' })
    h(0, '@tag.delimiter', { fg = '#585858' })
    h(0, '@tag.attribute', { link = 'Identifier' })
    h(0, '@storageclass.rust', { link = 'Keyword' })
    h(0, 'Macro', { fg = '#739393', italic = false })
    h(0, '@function.macro', { fg = '#a8aec1', italic = false })
    h(0, '@function.method.call', { fg = '#a8aec1', italic = false })
    h(0, '@function.method', { fg = '#a8aec1', italic = false })
    h(0, '@function.call', { fg = '#a8aec1', italic = false })
    h(0, '@function.builtin', { fg = '#a8aec1', italic = false })
    h(0, '@function', { fg = '#a8aec1', italic = false })
    h(0, '@diff.plus', { link = 'DiffAdd' })
    h(0, 'DiffAdd', { bg = '#383E2A' })
    h(0, '@diff.minus', { link = 'DiffDelete' })
    h(0, 'DiffDelete', { bg = '#4C1919' })
    h(0, '@diff.delta', { link = 'DiffChange' })
    h(0, 'DiffChange', { bg = '#7e4e08' })
    h(0, '@constructor.lua', { link = 'Delimiter' })
    h(0, 'Delimiter', { fg = '#888888' })
    h(0, '@constructor', { link = 'Type' })
    h(0, 'Error', { bg = '#ab4642' })
    h(0, '@attribute', { link = 'Identifier' })
    h(0, 'Removed', { bg = '#ab4642', fg = '#d8d8d8' })
    h(0, 'Changed', { bg = '#dc9656', fg = '#d8d8d8' })
    h(0, 'Added', { bg = '#9EBC9F', fg = '#d8d8d8' })
    h(0, 'Todo', { bg = '#C493B0' })
    h(0, 'Underlined', { underline = true })
    h(0, 'Special', { fg = '#739393' })
    h(0, 'Typedef', { fg = '#a8a8a8' })
    h(0, 'StorageClass', { fg = '#a8a8a8' })
    h(0, 'PreCondit', { fg = '#739393', italic = false })
    h(0, 'Define', { fg = '#739393', italic = false })
    h(0, 'Include', { fg = '#739393', italic = false })
    h(0, 'PreProc', { fg = '#739393', italic = false })
    h(0, 'Exception', { fg = '#739393', italic = false })
    h(0, 'Label', { fg = '#739393', italic = false })
    h(0, 'Repeat', { fg = '#739393', italic = false })
    h(0, 'Conditional', { fg = '#739393', italic = false })
    h(0, 'Comment', { fg = '#585858' })
    h(0, 'Float', { fg = '#d8d8d8' })
    h(0, 'Character', { fg = '#799496' })
    h(0, 'WinBarNC', { link = 'Comment' })
    h(0, 'WinBar', { link = 'Comment' })
    h(0, 'StatusLineNC', { bg = '#111111', fg = '#b8b8b8' })
    h(0, 'SpellRare', { fg = '#86c1b9', undercurl = true })
    h(0, 'SpellLocal', { fg = '#9EBC9F', undercurl = true })
    h(0, 'SpellCap', { fg = '#f7ca88', undercurl = true })
    h(0, 'SpellBad', { fg = '#ab4642', undercurl = true })
    h(0, 'Search', { bg = '#383838' })
    h(0, 'QuickFixLine', { link = 'Normal' })
    h(0, 'Question', { link = 'WarningMsg' })
    h(0, 'PmenuThumb', { bg = '#585858' })
    h(0, 'PmenuSbar', { bg = '#202020' })
    h(0, 'PmenuSel', { bg = '#282828', fg = '#d8d8d8' })
    h(0, 'NormalFloat', { bg = '#0e0e0e' })
    h(0, 'FloatBorder', { bg = '#0e0e0e', fg = '#585858' })
    h(0, 'NonText', { fg = '#383838' })
    h(0, 'MoreMsg', { link = 'WarningMsg' })
    h(0, 'ModeMsg', { fg = '#9EBC9F' })
    h(0, 'MatchParen', { bg = '#383838', underline = true })
    h(0, 'CursorLineNr', { bg = '#0e0e0e', fg = '#c8c8c8' })
    h(0, 'LineNr', { bg = '#0e0e0e', fg = '#585858' })
    h(0, 'Folded', { bg = '#383838' })
    h(0, 'WinSeparator', { bg = '#0e0e0e', fg = '#585858' })
    h(0, 'DiffText', { bg = '#383E2A' })
    h(0, 'CursorLine', { bg = '#0e0e0e' })
    h(0, 'CursorColumn', { bg = '#282828' })
    h(0, 'Cursor', { bg = '#c8c8c8', fg = '#0e0e0e' })
    h(0, 'CurSearch', { bg = '#383838' })
    h(0, 'Conceal', { fg = '#585858' })
    h(0, 'ColorColumn', { bg = '#585858' })
    h(0, 'Function', { fg = '#a8aec1', italic = false })
    h(0, 'StatusLineUnsavedFileIcon', { bg = '#111111', fg = '#f7ca88' })
    h(0, 'StatusLineGitDiffChanged', { bg = '#161616', fg = '#f7ca88' })
    h(0, 'StatusLineLspHint', { bg = '#161616', fg = '#86c1b9' })
    h(
        0,
        'DiagnosticUnnecessary',
        { fg = '#585858', special = '#86c1b9', undercurl = true }
    )
    h(0, 'DiagnosticDeprecated', { strikethrough = true })
    h(0, 'DiagnosticSignHint', { link = 'DiagnosticHint' })
    h(0, 'DiagnosticSignInfo', { link = 'DiagnosticInfo' })
    h(0, 'DiagnosticSignWarn', { link = 'DiagnosticWarn' })
    h(0, 'DiagnosticSignError', { link = 'DiagnosticError' })
    h(0, 'DiagnosticFloatingHint', { link = 'DiagnosticHint' })
    h(0, 'DiagnosticFloatingInfo', { link = 'DiagnosticInfo' })
    h(0, 'Keyword', { fg = '#739393', italic = false })
    h(0, 'DiagnosticFloatingWarn', { link = 'DiagnosticWarn' })
    h(0, 'DiagnosticUnderlineHint', { special = '#86c1b9', undercurl = true })
    h(0, 'DiagnosticUnderlineInfo', { special = '#739393', undercurl = true })
    h(0, 'DiagnosticUnderlineWarn', { special = '#f7ca88', undercurl = true })
    h(0, 'DiagnosticUnderlineError', { special = '#ab4642', undercurl = true })
    h(0, 'DiagnosticVirtualTextOk', { link = 'DiagnosticOk' })
    h(0, 'StatusLine', { bg = '#111111', fg = '#b8b8b8' })
    h(0, 'DiagnosticVirtualTextHint', { link = 'DiagnosticHint' })
    h(0, 'StatusLineMode', { bg = '#76946A', fg = '#111111' })
    h(0, 'DiagnosticVirtualTextInfo', { link = 'DiagnosticInfo' })
    h(0, 'DiagnosticVirtualTextWarn', { link = 'DiagnosticWarn' })
    h(0, 'DiagnosticVirtualTextError', { link = 'DiagnosticError' })
    h(0, '@lsp.typemod.enumMember.defaultLibrary', { link = 'Keyword' })
    h(0, '@lsp.type.variable', { link = '@lsp' })
    h(0, '@lsp.type.namespace', { link = 'Identifier' })
    h(0, '@lsp.type.macro', { link = 'Macro' })
    h(0, '@lsp.type.keyword', { link = 'Keyword' })
    h(0, 'LspInlayHint', { link = 'Comment' })
    h(0, 'LspCodeLensSeparator', { link = 'Comment' })
    h(0, 'LspCodeLens', { link = 'Comment' })
    h(0, 'LspReferenceWrite', { bg = '#383838', underline = true })
    h(0, 'LspReferenceRead', { bg = '#383838' })
    h(0, 'LspReferenceText', { bg = '#383838' })
    h(0, '@variable.builtin', { link = 'Identifier' })
    h(0, '@variable', { link = 'Identifier' })
    h(0, '@type.qualifier', { link = 'Keyword' })
    h(0, '@type.builtin', { fg = '#739393', italic = false })
    h(0, '@type.definition', { fg = '#a8a8a8', italic = false })
    h(0, '@type', { fg = '#a8a8a8', italic = false })
    h(0, '@module', { link = 'Identifier' })
    h(0, 'Operator', { fg = '#739393' })
    h(0, '@constant.builtin', { fg = '#739393', italic = false })
    h(0, 'Statement', { fg = '#739393', italic = false })
    h(0, 'Identifier', { fg = '#c8c8c8' })
    h(0, 'Boolean', { fg = '#739393', italic = false })
    h(0, 'Constant', { fg = '#c8c8c8' })
    h(0, 'Pmenu', { bg = '#202020', fg = '#5c5c5c' })
else
    h(0, 'Directory', { fg = '#346969' })
    h(0, 'Normal', { bg = '#ffffff', fg = '#111111' })
    h(0, 'DiagnosticOk', { fg = '#76946A' })
    h(0, 'ErrorMsg', { fg = '#ab4642' })
    h(0, 'String', { fg = '#548b40', italic = false })
    h(0, 'StatusLineGitBranchIcon', { bg = '#b8b8b8', fg = '#cc6d00' })
    h(0, 'StatusLineGitDiffRemoved', { bg = '#b8b8b8', fg = '#ab4642' })
    h(0, 'Number', { fg = '#202020' })
    h(0, 'StatusLineGitDiffAdded', { bg = '#b8b8b8', fg = '#4C5B2B' })
    h(0, 'StatusLineLspInactive', { bg = '#c8c8c8', fg = '#ab4642' })
    h(0, 'StatusLineLspActive', { bg = '#b8b8b8', fg = '#76946A' })
    h(0, 'StatusLineLspMessages', { bg = '#c8c8c8', fg = '#346969' })
    h(0, 'StatusLineLspInfo', { bg = '#b8b8b8', fg = '#346969' })
    h(0, 'Title', { fg = '#111111' })
    h(0, 'StatusLineLspWarn', { bg = '#b8b8b8', fg = '#b08508' })
    h(0, 'StatusLineLspError', { bg = '#b8b8b8', fg = '#ab4642' })
    h(0, 'StatusLineNeovimLogo', { bg = '#9EBC9F', fg = '#111111' })
    h(0, 'StatusLineMedium', { bg = '#b8b8b8', fg = '#383838' })
    h(0, 'DiagnosticFloatingError', { link = 'DiagnosticError' })
    h(0, 'Visual', { bg = '#c8c8c8' })
    h(0, 'Type', { fg = '#383838', italic = false })
    h(0, 'Structure', { fg = '#383838' })
    h(0, 'DiagnosticSignOk', { link = 'DiagnosticOk' })
    h(0, 'DiagnosticHint', { fg = '#86c1b9' })
    h(0, 'DiagnosticInfo', { fg = '#346969' })
    h(0, 'DiagnosticWarn', { fg = '#b08508' })
    h(0, 'DiagnosticError', { fg = '#ab4642' })
    h(0, 'DiagnosticFloatingOk', { link = 'DiagnosticOk' })
    h(0, 'DiagnosticUnderlineOk', { special = '#76946A', undercurl = true })
    h(0, 'WarningMsg', { fg = '#b08508' })
    h(0, '@lsp.typemod.keyword.async', { link = 'Keyword' })
    h(0, '@tag.tsx', { link = 'Type' })
    h(0, '@tag.javascript', { link = 'Type' })
    h(0, '@tag.delimiter', { fg = '#585858' })
    h(0, '@tag.attribute', { link = 'Identifier' })
    h(0, '@storageclass.rust', { link = 'Keyword' })
    h(0, 'Macro', { fg = '#346969' })
    h(0, '@function.macro', { fg = '#5E698E', italic = false })
    h(0, '@function.method.call', { fg = '#5E698E', italic = false })
    h(0, '@function.method', { fg = '#5E698E', italic = false })
    h(0, '@function.call', { fg = '#5E698E', italic = false })
    h(0, '@function.builtin', { fg = '#5E698E', italic = false })
    h(0, '@function', { fg = '#5E698E', italic = false })
    h(0, '@diff.plus', { link = 'DiffAdd' })
    h(0, 'DiffAdd', { bg = '#EBF1DD' })
    h(0, '@diff.minus', { link = 'DiffDelete' })
    h(0, 'DiffDelete', { bg = '#FFCCCC' })
    h(0, '@diff.delta', { link = 'DiffChange' })
    h(0, 'DiffChange', { bg = '#f7ca88' })
    h(0, '@constructor.lua', { link = 'Delimiter' })
    h(0, 'Delimiter', { fg = '#888888' })
    h(0, '@constructor', { link = 'Type' })
    h(0, 'Error', { bg = '#ab4642' })
    h(0, '@attribute', { link = 'Identifier' })
    h(0, 'Removed', { bg = '#ab4642', fg = '#d8d8d8' })
    h(0, 'Changed', { bg = '#dc9656', fg = '#d8d8d8' })
    h(0, 'Added', { bg = '#9EBC9F', fg = '#d8d8d8' })
    h(0, 'Todo', { bg = '#C493B0' })
    h(0, 'Underlined', { underline = true })
    h(0, 'Special', { fg = '#346969' })
    h(0, 'Typedef', { fg = '#383838' })
    h(0, 'StorageClass', { fg = '#383838' })
    h(0, 'PreCondit', { fg = '#346969' })
    h(0, 'Define', { fg = '#346969' })
    h(0, 'Include', { fg = '#346969' })
    h(0, 'PreProc', { fg = '#346969' })
    h(0, 'Exception', { fg = '#346969' })
    h(0, 'Label', { fg = '#346969' })
    h(0, 'Repeat', { fg = '#346969' })
    h(0, 'Conditional', { fg = '#346969' })
    h(0, 'Comment', { fg = '#5c5c5c' })
    h(0, 'Float', { fg = '#202020' })
    h(0, 'Character', { fg = '#799496' })
    h(0, 'WinBarNC', { link = 'Comment' })
    h(0, 'WinBar', { link = 'Comment' })
    h(0, 'StatusLineNC', { bg = '#c8c8c8', fg = '#383838' })
    h(0, 'SpellRare', { fg = '#86c1b9', undercurl = true })
    h(0, 'SpellLocal', { fg = '#9EBC9F', undercurl = true })
    h(0, 'SpellCap', { fg = '#f7ca88', undercurl = true })
    h(0, 'SpellBad', { fg = '#ab4642', undercurl = true })
    h(0, 'Search', { bg = '#c8c8c8' })
    h(0, 'QuickFixLine', { link = 'Normal' })
    h(0, 'Question', { link = 'WarningMsg' })
    h(0, 'PmenuThumb', { bg = '#585858' })
    h(0, 'PmenuSbar', { bg = '#202020' })
    h(0, 'PmenuSel', { bg = '#c8c8c8', fg = '#161616' })
    h(0, 'NormalFloat', { bg = '#ffffff' })
    h(0, 'FloatBorder', { bg = '#ffffff', fg = '#585858' })
    h(0, 'NonText', { fg = '#b8b8b8' })
    h(0, 'MoreMsg', { link = 'WarningMsg' })
    h(0, 'ModeMsg', { fg = '#9EBC9F' })
    h(0, 'MatchParen', { bg = '#c8c8c8', underline = true })
    h(0, 'CursorLineNr', { bg = '#ffffff', fg = '#111111' })
    h(0, 'LineNr', { bg = '#ffffff', fg = '#888888' })
    h(0, 'Folded', { bg = '#383838' })
    h(0, 'WinSeparator', { bg = '#ffffff', fg = '#585858' })
    h(0, 'DiffText', { bg = '#EBF1DD' })
    h(0, 'CursorLine', { bg = '#ffffff' })
    h(0, 'CursorColumn', { bg = '#282828' })
    h(0, 'Cursor', { bg = '#111111', fg = '#ffffff' })
    h(0, 'CurSearch', { bg = '#c8c8c8' })
    h(0, 'Conceal', { fg = '#383838' })
    h(0, 'ColorColumn', { bg = '#888888' })
    h(0, 'Function', { fg = '#5E698E', italic = false })
    h(0, 'StatusLineUnsavedFileIcon', { bg = '#c8c8c8', fg = '#b08508' })
    h(0, 'StatusLineGitDiffChanged', { bg = '#b8b8b8', fg = '#b08508' })
    h(0, 'StatusLineLspHint', { bg = '#b8b8b8', fg = '#86c1b9' })
    h(
        0,
        'DiagnosticUnnecessary',
        { fg = '#585858', special = '#86c1b9', undercurl = true }
    )
    h(0, 'DiagnosticDeprecated', { strikethrough = true })
    h(0, 'DiagnosticSignHint', { link = 'DiagnosticHint' })
    h(0, 'DiagnosticSignInfo', { link = 'DiagnosticInfo' })
    h(0, 'DiagnosticSignWarn', { link = 'DiagnosticWarn' })
    h(0, 'DiagnosticSignError', { link = 'DiagnosticError' })
    h(0, 'DiagnosticFloatingHint', { link = 'DiagnosticHint' })
    h(0, 'DiagnosticFloatingInfo', { link = 'DiagnosticInfo' })
    h(0, 'Keyword', { fg = '#346969' })
    h(0, 'DiagnosticFloatingWarn', { link = 'DiagnosticWarn' })
    h(0, 'DiagnosticUnderlineHint', { special = '#86c1b9', undercurl = true })
    h(0, 'DiagnosticUnderlineInfo', { special = '#346969', undercurl = true })
    h(0, 'DiagnosticUnderlineWarn', { special = '#b08508', undercurl = true })
    h(0, 'DiagnosticUnderlineError', { special = '#ab4642', undercurl = true })
    h(0, 'DiagnosticVirtualTextOk', { link = 'DiagnosticOk' })
    h(0, 'StatusLine', { bg = '#c8c8c8', fg = '#383838' })
    h(0, 'DiagnosticVirtualTextHint', { link = 'DiagnosticHint' })
    h(0, 'StatusLineMode', { bg = '#9EBC9F', fg = '#111111' })
    h(0, 'DiagnosticVirtualTextInfo', { link = 'DiagnosticInfo' })
    h(0, 'DiagnosticVirtualTextWarn', { link = 'DiagnosticWarn' })
    h(0, 'DiagnosticVirtualTextError', { link = 'DiagnosticError' })
    h(0, '@lsp.typemod.enumMember.defaultLibrary', { link = 'Keyword' })
    h(0, '@lsp.type.variable', { link = '@lsp' })
    h(0, '@lsp.type.namespace', { link = 'Identifier' })
    h(0, '@lsp.type.macro', { link = 'Macro' })
    h(0, '@lsp.type.keyword', { link = 'Keyword' })
    h(0, 'LspInlayHint', { link = 'Comment' })
    h(0, 'LspCodeLensSeparator', { link = 'Comment' })
    h(0, 'LspCodeLens', { link = 'Comment' })
    h(0, 'LspReferenceWrite', { bg = '#c8c8c8', underline = true })
    h(0, 'LspReferenceRead', { bg = '#c8c8c8' })
    h(0, 'LspReferenceText', { bg = '#c8c8c8' })
    h(0, '@variable.builtin', { link = 'Identifier' })
    h(0, '@variable', { link = 'Identifier' })
    h(0, '@type.qualifier', { link = 'Keyword' })
    h(0, '@type.builtin', { fg = '#346969', italic = false })
    h(0, '@type.definition', { fg = '#383838', italic = false })
    h(0, '@type', { fg = '#383838', italic = false })
    h(0, '@module', { link = 'Identifier' })
    h(0, 'Operator', { fg = '#346969' })
    h(0, '@constant.builtin', { fg = '#346969', italic = false })
    h(0, 'Statement', { fg = '#346969' })
    h(0, 'Identifier', { fg = '#111111' })
    h(0, 'Boolean', { fg = '#346969' })
    h(0, 'Constant', { fg = '#111111' })
    h(0, 'Pmenu', { bg = '#b8b8b8', fg = '#787878' })
end
